// Code generated by goctl. DO NOT EDIT.
package types

type SearchBase struct {
	Keyword     string     `json:"keyword,optional"`               // 关键字
	Cursor      int64      `json:"cursor,optional"`                // 游标,基于游标分页时使用
	CursorAsc   bool       `json:"cursorAsc,optional"`             // 游标分页时方向 true:asc  false:desc
	PageSize    int        `json:"pageSize,default=20,optional"`   // 每页条数
	PageCurrent int        `json:"pageCurrent,default=1,optional"` // 当前页
	OrderSort   []string   `json:"orderSort,optional"`             // 排序 eg： ["create_time asc", "id desc"]
	SearchPlus  [][]string `json:"searchPlus,optional"`            // 加强版搜索参数  eg: [["p_id", "=", "a", "string"], ["complete_time", ">=", "1674373544","number"]]
}

type PageBase struct {
	Total       int64 `json:"total,omitempty"`       // 总条数
	PageCurrent int   `json:"pageCurrent,omitempty"` // 当前页
	PageSize    int   `json:"pageSize,omitempty"`    // 分页大小
	PageTotal   int   `json:"pageTotal,omitempty"`   // 总分页数
	LastCursor  int64 `json:"lastCursor,omitempty"`  // 使用游标分页时, 返回最后一个游标
}

type IdReq struct {
	Id int64 `json:"id"`
}

type IdsReq struct {
	Ids []int64 `json:"ids"`
}

type MArtifactView struct {
	Id             int64  `json:"id,optional"`             //制品id
	Name           string `json:"name,optional"`           //制品名称
	Source         int64  `json:"source,optional"`         //制品来源(1-客户端，2-服务端)
	Version        string `json:"version,optional"`        //制品版本信息
	CommitId       string `json:"commitId,optional"`       //git提交id
	CommitBranch   string `json:"commitBranch,optional"`   //git提交分支
	CompleteTime   string `json:"completeTime,optional"`   //制品制造完成时间
	DownloadAddr   string `json:"downloadAddr,optional"`   //下载地址
	QaStatus       int64  `json:"qaStatus,optional"`       //qa状态(1-未qa，2-qa中，3-qa失败，4-qa通过)
	PushStatus     int64  `json:"pushStatus,optional"`     //发布状态(1-未发布，2-发布中，3-发布失败，4-发布成功)
	DetailInfo     string `json:"detailInfo,optional"`     //jenkins输出详情
	CreateUser     string `json:"createUser,optional"`     //制品创建者
	DeleteState    int64  `json:"deleteState,optional"`    //
	DeleteTime     string `json:"deleteTime,optional"`     //
	CreateTime     string `json:"createTime,optional"`     //创建时间
	UpdateTime     string `json:"updateTime,optional"`     //更新时间
	Ext1           string `json:"ext1,optional"`           //扩展字段
	Ext2           string `json:"ext2,optional"`           //扩展字段
	Ext3           string `json:"ext3,optional"`           //扩展字段
	Ext4           string `json:"ext4,optional"`           //扩展字段
	ExtInfo        string `json:"extInfo,optional"`        //扩展信息
	ProjectId      int64  `json:"projectId,optional"`      //所属项目id
	ArtifactTypeId int64  `json:"artifactTypeId,optional"` //制品类型id
	EnvId          int64  `json:"envId,optional"`          //环境id
	EnvRecord      string `json:"envRecord,optional"`      //环境变更记录
	Code           string `json:"code,optional"`           //不能重复
}

type MArtifactTypeView struct {
	Id          int64  `json:"id,optional"`          //
	CreateUser  int64  `json:"createUser,optional"`  //创建者id
	CreateTime  string `json:"createTime,optional"`  //
	UpdateTime  string `json:"updateTime,optional"`  //
	DeleteTime  string `json:"deleteTime,optional"`  //
	DeleteState int64  `json:"deleteState,optional"` //
	Name        string `json:"name,optional"`        //分类名称
	Status      int64  `json:"status,optional"`      //分类状态 1启用 2停用
	Des         string `json:"des,optional"`         //描述
}

type MBugView struct {
	Id              int64  `json:"id,optional"`              //
	ProjectId       int64  `json:"projectId,optional"`       //所属项目id
	CreateUser      int64  `json:"createUser,optional"`      //
	CreateTime      string `json:"createTime,optional"`      //
	UpdateTime      string `json:"updateTime,optional"`      //
	DeleteTime      string `json:"deleteTime,optional"`      //
	DeleteState     int64  `json:"deleteState,optional"`     //
	MasterVersionId int64  `json:"masterVersionId,optional"` //迭代版本号
	SourceKind      int64  `json:"sourceKind,optional"`      //bug来源（1制品、2版本、3其他）
	SourceId        int64  `json:"sourceId,optional"`        //来源id
	SourceName      string `json:"sourceName,optional"`      //来源名字
	EnvId           int64  `json:"envId,optional"`           //环境id
	Feedback        string `json:"feedback,optional"`        //反馈者
	Kind            string `json:"kind,optional"`            //bug类型
	Os              string `json:"os,optional"`              //操作系统（all、pc、ios、android）
	Serious         string `json:"serious,optional"`         //严重程度1.2.3.4,越大越重
	Priority        string `json:"priority,optional"`        //优先级1.2.3.4,越大越高
	Title           string `json:"title,optional"`           //bug名称
	Des             string `json:"des,optional"`             //bug描述
	Status          string `json:"status,optional"`          //状态
	Solve           string `json:"solve,optional"`           //解决方案
	CommitTime      string `json:"commitTime,optional"`      //bug提交提交时间
	Appear          string `json:"appear,optional"`          //发现版本
	TitleUrl        string `json:"titleUrl,optional"`        //标题超链接
	IdUrl           string `json:"idUrl,optional"`           //id超链接
	UploadTime      string `json:"uploadTime,optional"`      //上传时间
}

type MEnvView struct {
	Id          int64  `json:"id,optional"`          //
	CreateUser  int64  `json:"createUser,optional"`  //创建者id
	CreateTime  string `json:"createTime,optional"`  //
	UpdateTime  string `json:"updateTime,optional"`  //
	DeleteTime  string `json:"deleteTime,optional"`  //
	DeleteState int64  `json:"deleteState,optional"` //
	Name        string `json:"name,optional"`        //环境名称
	Status      int64  `json:"status,optional"`      //环境状态 1启用 2停用
	Des         string `json:"des,optional"`         //环境描述
	Expire      int64  `json:"expire,optional"`      //过期时间(时),-1永不过期
}

type MExternalDiffRecordsView struct {
	Id              int64  `json:"id,optional"`              //
	ProjectId       int64  `json:"projectId,optional"`       //
	TaskId          string `json:"taskId,optional"`          //
	StartArtifactId int64  `json:"startArtifactId,optional"` //
	StartCommit     string `json:"startCommit,optional"`     //
	StartTs         int64  `json:"startTs,optional"`         //
	EndArtifactId   int64  `json:"endArtifactId,optional"`   //
	EndCommit       string `json:"endCommit,optional"`       //
	EndTs           int64  `json:"endTs,optional"`           //
	Type            string `json:"type,optional"`            //
	LogFilePath     string `json:"logFilePath,optional"`     //
	DiffFilePath    string `json:"diffFilePath,optional"`    //
	Status          string `json:"status,optional"`          //
	CreatedAt       string `json:"createdAt,optional"`       //
	UpdatedAt       string `json:"updatedAt,optional"`       //
	DeletedAt       string `json:"deletedAt,optional"`       //
}

type MExternalServerView struct {
	Id        int64  `json:"id,optional"`        //
	Type      string `json:"type,optional"`      //
	Name      string `json:"name,optional"`      //
	Proj      string `json:"proj,optional"`      //
	Addr      string `json:"addr,optional"`      //
	Desc      string `json:"desc,optional"`      //
	ApiMap    string `json:"apiMap,optional"`    //
	Attach    string `json:"attach,optional"`    //
	CreatedAt string `json:"createdAt,optional"` //
	UpdatedAt string `json:"updatedAt,optional"` //
	DeletedAt string `json:"deletedAt,optional"` //
}

type MExternalTaskView struct {
	Id        int64  `json:"id,optional"`        //
	TaskId    string `json:"taskId,optional"`    //
	Type      string `json:"type,optional"`      //
	Code      int64  `json:"code,optional"`      //
	Res       string `json:"res,optional"`       //
	Attach    string `json:"attach,optional"`    //
	CreatedAt string `json:"createdAt,optional"` //
	UpdatedAt string `json:"updatedAt,optional"` //
	DeletedAt string `json:"deletedAt,optional"` //
}

type MMasterVersionView struct {
	Id          int64  `json:"id,optional"`          //
	CreateUser  int64  `json:"createUser,optional"`  //创建者id
	CreateTime  string `json:"createTime,optional"`  //
	UpdateTime  string `json:"updateTime,optional"`  //
	DeleteTime  string `json:"deleteTime,optional"`  //
	DeleteState int64  `json:"deleteState,optional"` //
	ProjectId   int64  `json:"projectId,optional"`   //关联项目id
	Name        string `json:"name,optional"`        //名称
	VersionNum  string `json:"versionNum,optional"`  //版本代号
	Status      int64  `json:"status,optional"`      //环境状态 1启用 2停用
	Des         string `json:"des,optional"`         //清单描述
}

type MProjectView struct {
	Id          int64  `json:"id,optional"`          //
	CreateUser  int64  `json:"createUser,optional"`  //创建者id
	CreateTime  string `json:"createTime,optional"`  //
	UpdateTime  string `json:"updateTime,optional"`  //
	DeleteTime  string `json:"deleteTime,optional"`  //
	DeleteState int64  `json:"deleteState,optional"` //
	Name        string `json:"name,optional"`        //项目名称
	Des         string `json:"des,optional"`         //
	Status      int64  `json:"status,optional"`      //状态(1启用，2停用)
}

type MTypeMapView struct {
	Id          int64  `json:"id,optional"`          //
	CreateUser  int64  `json:"createUser,optional"`  //id
	CreateTime  string `json:"createTime,optional"`  //
	UpdateTime  string `json:"updateTime,optional"`  //
	DeleteTime  string `json:"deleteTime,optional"`  //
	DeleteState int64  `json:"deleteState,optional"` //
	Pid         int64  `json:"pid,optional"`         //上级分类id
	Name        string `json:"name,optional"`        //类型名称
	Des         string `json:"des,optional"`         //描述
	Status      int64  `json:"status,optional"`      //状态(1启用用，2停用)
	Ext1        string `json:"ext1,optional"`        //
	Ext2        string `json:"ext2,optional"`        //
	Ext3        string `json:"ext3,optional"`        //
}

type MVersionView struct {
	Id          int64  `json:"id,optional"`          //id
	VersionNum  string `json:"versionNum,optional"`  //版本号
	ServerId    string `json:"serverId,optional"`    //服务器
	ImageId     string `json:"imageId,optional"`     //镜像id
	ApkId       int64  `json:"apkId,optional"`       //apk包id
	BundleId    string `json:"bundleId,optional"`    //bundle_id
	DataId      string `json:"dataId,optional"`      //数据档id
	QaStatus    int64  `json:"qaStatus,optional"`    //qa状态(1-未qa，2-qa中，3-qa失败，4-qa通过)
	PushStatus  int64  `json:"pushStatus,optional"`  //发布状态(1-未发布，2-发布中，3-发布失败，4-发布成功)
	BugInfo     string `json:"bugInfo,optional"`     //bug信息
	Des         string `json:"des,optional"`         //描述
	ProjectId   int64  `json:"projectId,optional"`   //所属项目id
	EnvId       int64  `json:"envId,optional"`       //环境id
	CreateUser  string `json:"createUser,optional"`  //制品创建者
	DeleteState int64  `json:"deleteState,optional"` //
	DeleteTime  string `json:"deleteTime,optional"`  //
	CreateTime  string `json:"createTime,optional"`  //创建时间
	UpdateTime  string `json:"updateTime,optional"`  //更新时间
	Ext1        string `json:"ext1,optional"`        //扩展字段
	Ext2        string `json:"ext2,optional"`        //扩展字段
	Ext3        string `json:"ext3,optional"`        //扩展字段
	Ext4        string `json:"ext4,optional"`        //扩展字段
	Pid         int64  `json:"pid,optional"`         //父版本id
	Name        string `json:"name,optional"`        //名称
}

type CreateMArtifactReq struct {
	Name           string `json:"name"`                  //制品名称
	Source         int64  `json:"source,default=0"`      //制品来源(1-客户端，2-服务端)
	Version        string `json:"version"`               //制品版本信息
	CommitId       string `json:"commitId"`              //git提交id
	CommitBranch   string `json:"commitBranch"`          //git提交分支
	CompleteTime   string `json:"completeTime,optional"` //制品制造完成时间
	DownloadAddr   string `json:"downloadAddr"`          //下载地址
	QaStatus       int64  `json:"qaStatus,default=1"`    //qa状态(1-未qa，2-qa中，3-qa失败，4-qa通过)
	PushStatus     int64  `json:"pushStatus,default=1"`  //发布状态(1-未发布，2-发布中，3-发布失败，4-发布成功)
	DetailInfo     string `json:"detailInfo"`            //jenkins输出详情
	CreateUser     string `json:"createUser"`            //制品创建者
	DeleteState    int64  `json:"deleteState,default=0"` //
	DeleteTime     string `json:"deleteTime,optional"`   //
	Ext1           string `json:"ext1,optional"`         //扩展字段
	Ext2           string `json:"ext2,optional"`         //扩展字段
	Ext3           string `json:"ext3,optional"`         //扩展字段
	Ext4           string `json:"ext4,optional"`         //扩展字段
	ExtInfo        string `json:"extInfo,optional"`      //扩展信息
	ProjectId      int64  `json:"projectId"`             //所属项目id
	ArtifactTypeId int64  `json:"artifactTypeId"`        //制品类型id
	EnvId          int64  `json:"envId"`                 //环境id
	EnvRecord      string `json:"envRecord"`             //环境变更记录
	Code           string `json:"code"`                  //不能重复
}

type CreateMArtifactResp struct {
}

type UpdateMArtifactReq struct {
	Id             int64  `json:"id"`                      //制品id
	Name           string `json:"name,optional"`           //制品名称
	Source         int64  `json:"source,optional"`         //制品来源(1-客户端，2-服务端)
	Version        string `json:"version,optional"`        //制品版本信息
	CommitId       string `json:"commitId,optional"`       //git提交id
	CommitBranch   string `json:"commitBranch,optional"`   //git提交分支
	CompleteTime   string `json:"completeTime,optional"`   //制品制造完成时间
	DownloadAddr   string `json:"downloadAddr,optional"`   //下载地址
	QaStatus       int64  `json:"qaStatus,optional"`       //qa状态(1-未qa，2-qa中，3-qa失败，4-qa通过)
	PushStatus     int64  `json:"pushStatus,optional"`     //发布状态(1-未发布，2-发布中，3-发布失败，4-发布成功)
	DetailInfo     string `json:"detailInfo,optional"`     //jenkins输出详情
	CreateUser     string `json:"createUser,optional"`     //制品创建者
	DeleteState    int64  `json:"deleteState,optional"`    //
	DeleteTime     string `json:"deleteTime,optional"`     //
	Ext1           string `json:"ext1,optional"`           //扩展字段
	Ext2           string `json:"ext2,optional"`           //扩展字段
	Ext3           string `json:"ext3,optional"`           //扩展字段
	Ext4           string `json:"ext4,optional"`           //扩展字段
	ExtInfo        string `json:"extInfo,optional"`        //扩展信息
	ProjectId      int64  `json:"projectId,optional"`      //所属项目id
	ArtifactTypeId int64  `json:"artifactTypeId,optional"` //制品类型id
	EnvId          int64  `json:"envId,optional"`          //环境id
	EnvRecord      string `json:"envRecord,optional"`      //环境变更记录
	Code           string `json:"code,optional"`           //不能重复
}

type UpdateMArtifactResp struct {
}

type DeleteMArtifactResp struct {
}

type DetailMArtifactResp struct {
	MArtifactView
}

type SearchMArtifactReq struct {
	SearchBase
	Id             int64  `json:"id,optional"`             //制品id
	Name           string `json:"name,optional"`           //制品名称
	Source         int64  `json:"source,optional"`         //制品来源(1-客户端，2-服务端)
	Version        string `json:"version,optional"`        //制品版本信息
	CommitId       string `json:"commitId,optional"`       //git提交id
	CommitBranch   string `json:"commitBranch,optional"`   //git提交分支
	CompleteTime   string `json:"completeTime,optional"`   //制品制造完成时间
	DownloadAddr   string `json:"downloadAddr,optional"`   //下载地址
	QaStatus       int64  `json:"qaStatus,optional"`       //qa状态(1-未qa，2-qa中，3-qa失败，4-qa通过)
	PushStatus     int64  `json:"pushStatus,optional"`     //发布状态(1-未发布，2-发布中，3-发布失败，4-发布成功)
	DetailInfo     string `json:"detailInfo,optional"`     //jenkins输出详情
	CreateUser     string `json:"createUser,optional"`     //制品创建者
	DeleteState    int64  `json:"deleteState,optional"`    //
	DeleteTime     string `json:"deleteTime,optional"`     //
	CreateTime     string `json:"createTime,optional"`     //创建时间
	UpdateTime     string `json:"updateTime,optional"`     //更新时间
	Ext1           string `json:"ext1,optional"`           //扩展字段
	Ext2           string `json:"ext2,optional"`           //扩展字段
	Ext3           string `json:"ext3,optional"`           //扩展字段
	Ext4           string `json:"ext4,optional"`           //扩展字段
	ExtInfo        string `json:"extInfo,optional"`        //扩展信息
	ProjectId      int64  `json:"projectId,optional"`      //所属项目id
	ArtifactTypeId int64  `json:"artifactTypeId,optional"` //制品类型id
	EnvId          int64  `json:"envId,optional"`          //环境id
	EnvRecord      string `json:"envRecord,optional"`      //环境变更记录
	Code           string `json:"code,optional"`           //不能重复
}

type SearchMArtifactResp struct {
	PageBase
	List []MArtifactView `json:"list"` // 列表
}

type CreateMArtifactTypeReq struct {
	CreateUser  int64  `json:"createUser,optional"`   //创建者id
	DeleteTime  string `json:"deleteTime,optional"`   //
	DeleteState int64  `json:"deleteState,default=0"` //
	Name        string `json:"name"`                  //分类名称
	Status      int64  `json:"status,default=1"`      //分类状态 1启用 2停用
	Des         string `json:"des,optional"`          //描述
}

type CreateMArtifactTypeResp struct {
}

type UpdateMArtifactTypeReq struct {
	Id          int64  `json:"id"`                   //
	CreateUser  int64  `json:"createUser,optional"`  //创建者id
	DeleteTime  string `json:"deleteTime,optional"`  //
	DeleteState int64  `json:"deleteState,optional"` //
	Name        string `json:"name,optional"`        //分类名称
	Status      int64  `json:"status,optional"`      //分类状态 1启用 2停用
	Des         string `json:"des,optional"`         //描述
}

type UpdateMArtifactTypeResp struct {
}

type DeleteMArtifactTypeResp struct {
}

type DetailMArtifactTypeResp struct {
	MArtifactTypeView
}

type SearchMArtifactTypeReq struct {
	SearchBase
	Id          int64  `json:"id,optional"`          //
	CreateUser  int64  `json:"createUser,optional"`  //创建者id
	CreateTime  string `json:"createTime,optional"`  //
	UpdateTime  string `json:"updateTime,optional"`  //
	DeleteTime  string `json:"deleteTime,optional"`  //
	DeleteState int64  `json:"deleteState,optional"` //
	Name        string `json:"name,optional"`        //分类名称
	Status      int64  `json:"status,optional"`      //分类状态 1启用 2停用
	Des         string `json:"des,optional"`         //描述
}

type SearchMArtifactTypeResp struct {
	PageBase
	List []MArtifactTypeView `json:"list"` // 列表
}

type CreateMBugReq struct {
	ProjectId       int64  `json:"projectId,default=0"`       //所属项目id
	CreateUser      int64  `json:"createUser,optional"`       //
	DeleteTime      string `json:"deleteTime,optional"`       //
	DeleteState     int64  `json:"deleteState,default=0"`     //
	MasterVersionId int64  `json:"masterVersionId,default=0"` //迭代版本号
	SourceKind      int64  `json:"sourceKind,default=0"`      //bug来源（1制品、2版本、3其他）
	SourceId        int64  `json:"sourceId,default=0"`        //来源id
	SourceName      string `json:"sourceName"`                //来源名字
	EnvId           int64  `json:"envId,default=0"`           //环境id
	Feedback        string `json:"feedback"`                  //反馈者
	Kind            string `json:"kind"`                      //bug类型
	Os              string `json:"os"`                        //操作系统（all、pc、ios、android）
	Serious         string `json:"serious,default=1"`         //严重程度1.2.3.4,越大越重
	Priority        string `json:"priority,default=1"`        //优先级1.2.3.4,越大越高
	Title           string `json:"title"`                     //bug名称
	Des             string `json:"des"`                       //bug描述
	Status          string `json:"status,default=1"`          //状态
	Solve           string `json:"solve"`                     //解决方案
	CommitTime      string `json:"commitTime,optional"`       //bug提交提交时间
	Appear          string `json:"appear"`                    //发现版本
	TitleUrl        string `json:"titleUrl"`                  //标题超链接
	IdUrl           string `json:"idUrl"`                     //id超链接
	UploadTime      string `json:"uploadTime"`                //上传时间
}

type CreateMBugResp struct {
}

type UpdateMBugReq struct {
	Id              int64  `json:"id"`                       //
	ProjectId       int64  `json:"projectId,optional"`       //所属项目id
	CreateUser      int64  `json:"createUser,optional"`      //
	DeleteTime      string `json:"deleteTime,optional"`      //
	DeleteState     int64  `json:"deleteState,optional"`     //
	MasterVersionId int64  `json:"masterVersionId,optional"` //迭代版本号
	SourceKind      int64  `json:"sourceKind,optional"`      //bug来源（1制品、2版本、3其他）
	SourceId        int64  `json:"sourceId,optional"`        //来源id
	SourceName      string `json:"sourceName,optional"`      //来源名字
	EnvId           int64  `json:"envId,optional"`           //环境id
	Feedback        string `json:"feedback,optional"`        //反馈者
	Kind            string `json:"kind,optional"`            //bug类型
	Os              string `json:"os,optional"`              //操作系统（all、pc、ios、android）
	Serious         string `json:"serious,optional"`         //严重程度1.2.3.4,越大越重
	Priority        string `json:"priority,optional"`        //优先级1.2.3.4,越大越高
	Title           string `json:"title,optional"`           //bug名称
	Des             string `json:"des,optional"`             //bug描述
	Status          string `json:"status,optional"`          //状态
	Solve           string `json:"solve,optional"`           //解决方案
	CommitTime      string `json:"commitTime,optional"`      //bug提交提交时间
	Appear          string `json:"appear,optional"`          //发现版本
	TitleUrl        string `json:"titleUrl,optional"`        //标题超链接
	IdUrl           string `json:"idUrl,optional"`           //id超链接
	UploadTime      string `json:"uploadTime,optional"`      //上传时间
}

type UpdateMBugResp struct {
}

type DeleteMBugResp struct {
}

type DetailMBugResp struct {
	MBugView
}

type SearchMBugReq struct {
	SearchBase
	Id              int64  `json:"id,optional"`              //
	ProjectId       int64  `json:"projectId,optional"`       //所属项目id
	CreateUser      int64  `json:"createUser,optional"`      //
	CreateTime      string `json:"createTime,optional"`      //
	UpdateTime      string `json:"updateTime,optional"`      //
	DeleteTime      string `json:"deleteTime,optional"`      //
	DeleteState     int64  `json:"deleteState,optional"`     //
	MasterVersionId int64  `json:"masterVersionId,optional"` //迭代版本号
	SourceKind      int64  `json:"sourceKind,optional"`      //bug来源（1制品、2版本、3其他）
	SourceId        int64  `json:"sourceId,optional"`        //来源id
	SourceName      string `json:"sourceName,optional"`      //来源名字
	EnvId           int64  `json:"envId,optional"`           //环境id
	Feedback        string `json:"feedback,optional"`        //反馈者
	Kind            string `json:"kind,optional"`            //bug类型
	Os              string `json:"os,optional"`              //操作系统（all、pc、ios、android）
	Serious         string `json:"serious,optional"`         //严重程度1.2.3.4,越大越重
	Priority        string `json:"priority,optional"`        //优先级1.2.3.4,越大越高
	Title           string `json:"title,optional"`           //bug名称
	Des             string `json:"des,optional"`             //bug描述
	Status          string `json:"status,optional"`          //状态
	Solve           string `json:"solve,optional"`           //解决方案
	CommitTime      string `json:"commitTime,optional"`      //bug提交提交时间
	Appear          string `json:"appear,optional"`          //发现版本
	TitleUrl        string `json:"titleUrl,optional"`        //标题超链接
	IdUrl           string `json:"idUrl,optional"`           //id超链接
	UploadTime      string `json:"uploadTime,optional"`      //上传时间
}

type SearchMBugResp struct {
	PageBase
	List []MBugView `json:"list"` // 列表
}

type CreateMEnvReq struct {
	CreateUser  int64  `json:"createUser,optional"`   //创建者id
	DeleteTime  string `json:"deleteTime,optional"`   //
	DeleteState int64  `json:"deleteState,default=0"` //
	Name        string `json:"name"`                  //环境名称
	Status      int64  `json:"status,default=1"`      //环境状态 1启用 2停用
	Des         string `json:"des,optional"`          //环境描述
	Expire      int64  `json:"expire,default=-1"`     //过期时间(时),-1永不过期
}

type CreateMEnvResp struct {
}

type UpdateMEnvReq struct {
	Id          int64  `json:"id"`                   //
	CreateUser  int64  `json:"createUser,optional"`  //创建者id
	DeleteTime  string `json:"deleteTime,optional"`  //
	DeleteState int64  `json:"deleteState,optional"` //
	Name        string `json:"name,optional"`        //环境名称
	Status      int64  `json:"status,optional"`      //环境状态 1启用 2停用
	Des         string `json:"des,optional"`         //环境描述
	Expire      int64  `json:"expire,optional"`      //过期时间(时),-1永不过期
}

type UpdateMEnvResp struct {
}

type DeleteMEnvResp struct {
}

type DetailMEnvResp struct {
	MEnvView
}

type SearchMEnvReq struct {
	SearchBase
	Id          int64  `json:"id,optional"`          //
	CreateUser  int64  `json:"createUser,optional"`  //创建者id
	CreateTime  string `json:"createTime,optional"`  //
	UpdateTime  string `json:"updateTime,optional"`  //
	DeleteTime  string `json:"deleteTime,optional"`  //
	DeleteState int64  `json:"deleteState,optional"` //
	Name        string `json:"name,optional"`        //环境名称
	Status      int64  `json:"status,optional"`      //环境状态 1启用 2停用
	Des         string `json:"des,optional"`         //环境描述
	Expire      int64  `json:"expire,optional"`      //过期时间(时),-1永不过期
}

type SearchMEnvResp struct {
	PageBase
	List []MEnvView `json:"list"` // 列表
}

type CreateMExternalDiffRecordsReq struct {
	ProjectId       int64  `json:"projectId,optional"`       //
	TaskId          string `json:"taskId,optional"`          //
	StartArtifactId int64  `json:"startArtifactId,optional"` //
	StartCommit     string `json:"startCommit,optional"`     //
	StartTs         int64  `json:"startTs,optional"`         //
	EndArtifactId   int64  `json:"endArtifactId,optional"`   //
	EndCommit       string `json:"endCommit,optional"`       //
	EndTs           int64  `json:"endTs,optional"`           //
	Type            string `json:"type,optional"`            //
	LogFilePath     string `json:"logFilePath,optional"`     //
	DiffFilePath    string `json:"diffFilePath,optional"`    //
	Status          string `json:"status,optional"`          //
	CreatedAt       string `json:"createdAt,optional"`       //
	UpdatedAt       string `json:"updatedAt,optional"`       //
	DeletedAt       string `json:"deletedAt,optional"`       //
}

type CreateMExternalDiffRecordsResp struct {
}

type UpdateMExternalDiffRecordsReq struct {
	Id              int64  `json:"id"`                       //
	ProjectId       int64  `json:"projectId,optional"`       //
	TaskId          string `json:"taskId,optional"`          //
	StartArtifactId int64  `json:"startArtifactId,optional"` //
	StartCommit     string `json:"startCommit,optional"`     //
	StartTs         int64  `json:"startTs,optional"`         //
	EndArtifactId   int64  `json:"endArtifactId,optional"`   //
	EndCommit       string `json:"endCommit,optional"`       //
	EndTs           int64  `json:"endTs,optional"`           //
	Type            string `json:"type,optional"`            //
	LogFilePath     string `json:"logFilePath,optional"`     //
	DiffFilePath    string `json:"diffFilePath,optional"`    //
	Status          string `json:"status,optional"`          //
	CreatedAt       string `json:"createdAt,optional"`       //
	UpdatedAt       string `json:"updatedAt,optional"`       //
	DeletedAt       string `json:"deletedAt,optional"`       //
}

type UpdateMExternalDiffRecordsResp struct {
}

type DeleteMExternalDiffRecordsResp struct {
}

type DetailMExternalDiffRecordsResp struct {
	MExternalDiffRecordsView
}

type SearchMExternalDiffRecordsReq struct {
	SearchBase
	Id              int64  `json:"id,optional"`              //
	ProjectId       int64  `json:"projectId,optional"`       //
	TaskId          string `json:"taskId,optional"`          //
	StartArtifactId int64  `json:"startArtifactId,optional"` //
	StartCommit     string `json:"startCommit,optional"`     //
	StartTs         int64  `json:"startTs,optional"`         //
	EndArtifactId   int64  `json:"endArtifactId,optional"`   //
	EndCommit       string `json:"endCommit,optional"`       //
	EndTs           int64  `json:"endTs,optional"`           //
	Type            string `json:"type,optional"`            //
	LogFilePath     string `json:"logFilePath,optional"`     //
	DiffFilePath    string `json:"diffFilePath,optional"`    //
	Status          string `json:"status,optional"`          //
	CreatedAt       string `json:"createdAt,optional"`       //
	UpdatedAt       string `json:"updatedAt,optional"`       //
	DeletedAt       string `json:"deletedAt,optional"`       //
}

type SearchMExternalDiffRecordsResp struct {
	PageBase
	List []MExternalDiffRecordsView `json:"list"` // 列表
}

type CreateMExternalServerReq struct {
	Type      string `json:"type,optional"`      //
	Name      string `json:"name,optional"`      //
	Proj      string `json:"proj,optional"`      //
	Addr      string `json:"addr,optional"`      //
	Desc      string `json:"desc,optional"`      //
	ApiMap    string `json:"apiMap,optional"`    //
	Attach    string `json:"attach,optional"`    //
	CreatedAt string `json:"createdAt,optional"` //
	UpdatedAt string `json:"updatedAt,optional"` //
	DeletedAt string `json:"deletedAt,optional"` //
}

type CreateMExternalServerResp struct {
}

type UpdateMExternalServerReq struct {
	Id        int64  `json:"id"`                 //
	Type      string `json:"type,optional"`      //
	Name      string `json:"name,optional"`      //
	Proj      string `json:"proj,optional"`      //
	Addr      string `json:"addr,optional"`      //
	Desc      string `json:"desc,optional"`      //
	ApiMap    string `json:"apiMap,optional"`    //
	Attach    string `json:"attach,optional"`    //
	CreatedAt string `json:"createdAt,optional"` //
	UpdatedAt string `json:"updatedAt,optional"` //
	DeletedAt string `json:"deletedAt,optional"` //
}

type UpdateMExternalServerResp struct {
}

type DeleteMExternalServerResp struct {
}

type DetailMExternalServerResp struct {
	MExternalServerView
}

type SearchMExternalServerReq struct {
	SearchBase
	Id        int64  `json:"id,optional"`        //
	Type      string `json:"type,optional"`      //
	Name      string `json:"name,optional"`      //
	Proj      string `json:"proj,optional"`      //
	Addr      string `json:"addr,optional"`      //
	Desc      string `json:"desc,optional"`      //
	ApiMap    string `json:"apiMap,optional"`    //
	Attach    string `json:"attach,optional"`    //
	CreatedAt string `json:"createdAt,optional"` //
	UpdatedAt string `json:"updatedAt,optional"` //
	DeletedAt string `json:"deletedAt,optional"` //
}

type SearchMExternalServerResp struct {
	PageBase
	List []MExternalServerView `json:"list"` // 列表
}

type CreateMExternalTaskReq struct {
	TaskId    string `json:"taskId,optional"`    //
	Type      string `json:"type,optional"`      //
	Code      int64  `json:"code,optional"`      //
	Res       string `json:"res,optional"`       //
	Attach    string `json:"attach,optional"`    //
	CreatedAt string `json:"createdAt,optional"` //
	UpdatedAt string `json:"updatedAt,optional"` //
	DeletedAt string `json:"deletedAt,optional"` //
}

type CreateMExternalTaskResp struct {
}

type UpdateMExternalTaskReq struct {
	Id        int64  `json:"id"`                 //
	TaskId    string `json:"taskId,optional"`    //
	Type      string `json:"type,optional"`      //
	Code      int64  `json:"code,optional"`      //
	Res       string `json:"res,optional"`       //
	Attach    string `json:"attach,optional"`    //
	CreatedAt string `json:"createdAt,optional"` //
	UpdatedAt string `json:"updatedAt,optional"` //
	DeletedAt string `json:"deletedAt,optional"` //
}

type UpdateMExternalTaskResp struct {
}

type DeleteMExternalTaskResp struct {
}

type DetailMExternalTaskResp struct {
	MExternalTaskView
}

type SearchMExternalTaskReq struct {
	SearchBase
	Id        int64  `json:"id,optional"`        //
	TaskId    string `json:"taskId,optional"`    //
	Type      string `json:"type,optional"`      //
	Code      int64  `json:"code,optional"`      //
	Res       string `json:"res,optional"`       //
	Attach    string `json:"attach,optional"`    //
	CreatedAt string `json:"createdAt,optional"` //
	UpdatedAt string `json:"updatedAt,optional"` //
	DeletedAt string `json:"deletedAt,optional"` //
}

type SearchMExternalTaskResp struct {
	PageBase
	List []MExternalTaskView `json:"list"` // 列表
}

type CreateMMasterVersionReq struct {
	CreateUser  int64  `json:"createUser,optional"`   //创建者id
	DeleteTime  string `json:"deleteTime,optional"`   //
	DeleteState int64  `json:"deleteState,default=0"` //
	ProjectId   int64  `json:"projectId,default=0"`   //关联项目id
	Name        string `json:"name"`                  //名称
	VersionNum  string `json:"versionNum"`            //版本代号
	Status      int64  `json:"status,default=1"`      //环境状态 1启用 2停用
	Des         string `json:"des,optional"`          //清单描述
}

type CreateMMasterVersionResp struct {
}

type UpdateMMasterVersionReq struct {
	Id          int64  `json:"id"`                   //
	CreateUser  int64  `json:"createUser,optional"`  //创建者id
	DeleteTime  string `json:"deleteTime,optional"`  //
	DeleteState int64  `json:"deleteState,optional"` //
	ProjectId   int64  `json:"projectId,optional"`   //关联项目id
	Name        string `json:"name,optional"`        //名称
	VersionNum  string `json:"versionNum,optional"`  //版本代号
	Status      int64  `json:"status,optional"`      //环境状态 1启用 2停用
	Des         string `json:"des,optional"`         //清单描述
}

type UpdateMMasterVersionResp struct {
}

type DeleteMMasterVersionResp struct {
}

type DetailMMasterVersionResp struct {
	MMasterVersionView
}

type SearchMMasterVersionReq struct {
	SearchBase
	Id          int64  `json:"id,optional"`          //
	CreateUser  int64  `json:"createUser,optional"`  //创建者id
	CreateTime  string `json:"createTime,optional"`  //
	UpdateTime  string `json:"updateTime,optional"`  //
	DeleteTime  string `json:"deleteTime,optional"`  //
	DeleteState int64  `json:"deleteState,optional"` //
	ProjectId   int64  `json:"projectId,optional"`   //关联项目id
	Name        string `json:"name,optional"`        //名称
	VersionNum  string `json:"versionNum,optional"`  //版本代号
	Status      int64  `json:"status,optional"`      //环境状态 1启用 2停用
	Des         string `json:"des,optional"`         //清单描述
}

type SearchMMasterVersionResp struct {
	PageBase
	List []MMasterVersionView `json:"list"` // 列表
}

type CreateMProjectReq struct {
	CreateUser  int64  `json:"createUser,optional"`   //创建者id
	DeleteTime  string `json:"deleteTime,optional"`   //
	DeleteState int64  `json:"deleteState,default=0"` //
	Name        string `json:"name"`                  //项目名称
	Des         string `json:"des"`                   //
	Status      int64  `json:"status,default=1"`      //状态(1启用，2停用)
}

type CreateMProjectResp struct {
}

type UpdateMProjectReq struct {
	Id          int64  `json:"id"`                   //
	CreateUser  int64  `json:"createUser,optional"`  //创建者id
	DeleteTime  string `json:"deleteTime,optional"`  //
	DeleteState int64  `json:"deleteState,optional"` //
	Name        string `json:"name,optional"`        //项目名称
	Des         string `json:"des,optional"`         //
	Status      int64  `json:"status,optional"`      //状态(1启用，2停用)
}

type UpdateMProjectResp struct {
}

type DeleteMProjectResp struct {
}

type DetailMProjectResp struct {
	MProjectView
}

type SearchMProjectReq struct {
	SearchBase
	Id          int64  `json:"id,optional"`          //
	CreateUser  int64  `json:"createUser,optional"`  //创建者id
	CreateTime  string `json:"createTime,optional"`  //
	UpdateTime  string `json:"updateTime,optional"`  //
	DeleteTime  string `json:"deleteTime,optional"`  //
	DeleteState int64  `json:"deleteState,optional"` //
	Name        string `json:"name,optional"`        //项目名称
	Des         string `json:"des,optional"`         //
	Status      int64  `json:"status,optional"`      //状态(1启用，2停用)
}

type SearchMProjectResp struct {
	PageBase
	List []MProjectView `json:"list"` // 列表
}

type CreateMTypeMapReq struct {
	CreateUser  int64  `json:"createUser,optional"`   //id
	DeleteTime  string `json:"deleteTime,optional"`   //
	DeleteState int64  `json:"deleteState,default=0"` //
	Pid         int64  `json:"pid,default=0"`         //上级分类id
	Name        string `json:"name"`                  //类型名称
	Des         string `json:"des"`                   //描述
	Status      int64  `json:"status,default=1"`      //状态(1启用用，2停用)
	Ext1        string `json:"ext1,optional"`         //
	Ext2        string `json:"ext2,optional"`         //
	Ext3        string `json:"ext3,optional"`         //
}

type CreateMTypeMapResp struct {
}

type UpdateMTypeMapReq struct {
	Id          int64  `json:"id"`                   //
	CreateUser  int64  `json:"createUser,optional"`  //id
	DeleteTime  string `json:"deleteTime,optional"`  //
	DeleteState int64  `json:"deleteState,optional"` //
	Pid         int64  `json:"pid,optional"`         //上级分类id
	Name        string `json:"name,optional"`        //类型名称
	Des         string `json:"des,optional"`         //描述
	Status      int64  `json:"status,optional"`      //状态(1启用用，2停用)
	Ext1        string `json:"ext1,optional"`        //
	Ext2        string `json:"ext2,optional"`        //
	Ext3        string `json:"ext3,optional"`        //
}

type UpdateMTypeMapResp struct {
}

type DeleteMTypeMapResp struct {
}

type DetailMTypeMapResp struct {
	MTypeMapView
}

type SearchMTypeMapReq struct {
	SearchBase
	Id          int64  `json:"id,optional"`          //
	CreateUser  int64  `json:"createUser,optional"`  //id
	CreateTime  string `json:"createTime,optional"`  //
	UpdateTime  string `json:"updateTime,optional"`  //
	DeleteTime  string `json:"deleteTime,optional"`  //
	DeleteState int64  `json:"deleteState,optional"` //
	Pid         int64  `json:"pid,optional"`         //上级分类id
	Name        string `json:"name,optional"`        //类型名称
	Des         string `json:"des,optional"`         //描述
	Status      int64  `json:"status,optional"`      //状态(1启用用，2停用)
	Ext1        string `json:"ext1,optional"`        //
	Ext2        string `json:"ext2,optional"`        //
	Ext3        string `json:"ext3,optional"`        //
}

type SearchMTypeMapResp struct {
	PageBase
	List []MTypeMapView `json:"list"` // 列表
}

type CreateMVersionReq struct {
	VersionNum  string `json:"versionNum"`            //版本号
	ServerId    string `json:"serverId,default=0"`    //服务器
	ImageId     string `json:"imageId"`               //镜像id
	ApkId       int64  `json:"apkId,default=0"`       //apk包id
	BundleId    string `json:"bundleId"`              //bundle_id
	DataId      string `json:"dataId"`                //数据档id
	QaStatus    int64  `json:"qaStatus,default=1"`    //qa状态(1-未qa，2-qa中，3-qa失败，4-qa通过)
	PushStatus  int64  `json:"pushStatus,default=1"`  //发布状态(1-未发布，2-发布中，3-发布失败，4-发布成功)
	BugInfo     string `json:"bugInfo"`               //bug信息
	Des         string `json:"des"`                   //描述
	ProjectId   int64  `json:"projectId"`             //所属项目id
	EnvId       int64  `json:"envId"`                 //环境id
	CreateUser  string `json:"createUser"`            //制品创建者
	DeleteState int64  `json:"deleteState,default=0"` //
	DeleteTime  string `json:"deleteTime,optional"`   //
	Ext1        string `json:"ext1,optional"`         //扩展字段
	Ext2        string `json:"ext2,optional"`         //扩展字段
	Ext3        string `json:"ext3,optional"`         //扩展字段
	Ext4        string `json:"ext4,optional"`         //扩展字段
	Pid         int64  `json:"pid,default=0"`         //父版本id
	Name        string `json:"name"`                  //名称
}

type CreateMVersionResp struct {
}

type UpdateMVersionReq struct {
	Id          int64  `json:"id"`                   //id
	VersionNum  string `json:"versionNum,optional"`  //版本号
	ServerId    string `json:"serverId,optional"`    //服务器
	ImageId     string `json:"imageId,optional"`     //镜像id
	ApkId       int64  `json:"apkId,optional"`       //apk包id
	BundleId    string `json:"bundleId,optional"`    //bundle_id
	DataId      string `json:"dataId,optional"`      //数据档id
	QaStatus    int64  `json:"qaStatus,optional"`    //qa状态(1-未qa，2-qa中，3-qa失败，4-qa通过)
	PushStatus  int64  `json:"pushStatus,optional"`  //发布状态(1-未发布，2-发布中，3-发布失败，4-发布成功)
	BugInfo     string `json:"bugInfo,optional"`     //bug信息
	Des         string `json:"des,optional"`         //描述
	ProjectId   int64  `json:"projectId,optional"`   //所属项目id
	EnvId       int64  `json:"envId,optional"`       //环境id
	CreateUser  string `json:"createUser,optional"`  //制品创建者
	DeleteState int64  `json:"deleteState,optional"` //
	DeleteTime  string `json:"deleteTime,optional"`  //
	Ext1        string `json:"ext1,optional"`        //扩展字段
	Ext2        string `json:"ext2,optional"`        //扩展字段
	Ext3        string `json:"ext3,optional"`        //扩展字段
	Ext4        string `json:"ext4,optional"`        //扩展字段
	Pid         int64  `json:"pid,optional"`         //父版本id
	Name        string `json:"name,optional"`        //名称
}

type UpdateMVersionResp struct {
}

type DeleteMVersionResp struct {
}

type DetailMVersionResp struct {
	MVersionView
}

type SearchMVersionReq struct {
	SearchBase
	Id          int64  `json:"id,optional"`          //id
	VersionNum  string `json:"versionNum,optional"`  //版本号
	ServerId    string `json:"serverId,optional"`    //服务器
	ImageId     string `json:"imageId,optional"`     //镜像id
	ApkId       int64  `json:"apkId,optional"`       //apk包id
	BundleId    string `json:"bundleId,optional"`    //bundle_id
	DataId      string `json:"dataId,optional"`      //数据档id
	QaStatus    int64  `json:"qaStatus,optional"`    //qa状态(1-未qa，2-qa中，3-qa失败，4-qa通过)
	PushStatus  int64  `json:"pushStatus,optional"`  //发布状态(1-未发布，2-发布中，3-发布失败，4-发布成功)
	BugInfo     string `json:"bugInfo,optional"`     //bug信息
	Des         string `json:"des,optional"`         //描述
	ProjectId   int64  `json:"projectId,optional"`   //所属项目id
	EnvId       int64  `json:"envId,optional"`       //环境id
	CreateUser  string `json:"createUser,optional"`  //制品创建者
	DeleteState int64  `json:"deleteState,optional"` //
	DeleteTime  string `json:"deleteTime,optional"`  //
	CreateTime  string `json:"createTime,optional"`  //创建时间
	UpdateTime  string `json:"updateTime,optional"`  //更新时间
	Ext1        string `json:"ext1,optional"`        //扩展字段
	Ext2        string `json:"ext2,optional"`        //扩展字段
	Ext3        string `json:"ext3,optional"`        //扩展字段
	Ext4        string `json:"ext4,optional"`        //扩展字段
	Pid         int64  `json:"pid,optional"`         //父版本id
	Name        string `json:"name,optional"`        //名称
}

type SearchMVersionResp struct {
	PageBase
	List []MVersionView `json:"list"` // 列表
}
